name: linting and artifact
on: push

jobs: 
    lint:
        runs-on: ubuntu-latest
        name: Install node and lint
        steps: 
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Install node
              uses: actions/setup-node@v6
              with:
                node-version: 24

            - name: Lint
              run: |
                cd app
                npm i
                npm run lint
            
    artifact:
        runs-on: ubuntu-latest
        name: Create artifact
        needs: lint
        if: success()
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Zip app
              run: |
                zip -r myapp.zip app

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: myapp
                path: myapp.zip

